### PR TITLE
Added step, min & max to the input template

### PR DESCRIPTION
**Pull request by seangwright**
The `templateOptions` object for input type can have the properties `step`, `min` and `max` for when the type of the input, also specified in the `templateOptions`, is 'number'.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@sgwatgit, thank you for your contribution!

I could merge your pr but I think adding attributes with not always defined values is not a great idea. Also, these attributes would be available on all types of input, not just 'number' (correct me if I'm wrong).

There is always good idea to use apiCheck, it provides consistency.

You can look at this commit to see what I mean by that: https://github.com/formly-js/angular-formly-templates-material/commit/11c2c54554a5e7b83ecdc404f52c0a262daae42d

**Comment by seangwright** [comment]
@kamilkisiela Thanks for adding these properties in that commit.

I was not very familiar with the usage of ApiCheck until you mentioned it - then I went to looked at the repo for it and your commit and I agree that is a much better implementation.

**Comment by kamilkisiela** [comment]
@sgwatgit, if you have any other request feel free to submit an issue with description. This proposal for adding support for min, max and step attributes was excellent! It was definitely needed. Thanks for that!

**Comment by seangwright** [comment]
@kamilkisiela When i use the latest build with these updates I am receiving warnings from ApiCheck in my console.

```
angular-formly: formly-field type input for property templateOptions apiCheck failed! `step`
at `Argument 1/value` must be `oneOf["number"]` 
https://github.com/formly-js/angular-formly/blob/7.3.9/other/ERRORS_AND_WARNINGS.md#formly-field-type-apicheck-failed

You passed:
{
  "type": "number",
  "label": "Economic Variable - Dollar Amount",
  "step": 0.01
}

With the types:
{
  "type": "string",
  "label": "string",
  "step": "number"
}

The API calls for:
{
  "__apiCheckData": {
    "strict": false,
    "optional": false,
    "type": "shape"
  },
  "shape": {
    "step": {
      "__apiCheckData": {
        "optional": true,
        "type": "ifNot",
        "description": "specified only if type is also specified",
        "error": "THIS IS THE PROBLEM: `step` must be `oneOf[\"number\"]`"
      },
      "ifNot": {
        "__apiCheckData": {
          "optional": false,
          "type": "enum"
        },
        "enum": [
          "number"
        ]
      }
    }
  }
}
```

And here is my field definition

```
{
    key: 'economicCalculationVars[0]',
    type: 'input',
    templateOptions: {
        type: 'number',
        label: 'Economic Variable - Dollar Amount',
        step: .01
    },
    hideExpression: 'model.economicCalculationType.id != 1',
    expressionProperties: {
        'templateOptions.required': 'model.economicCalculationType.id == 1'
    },
    validators: {
        range: function($viewValue, $modelValue, scope) {
            return $viewValue > 0;
        }
    }
}
```

I have tried setting step to `.01`, `0.01`, `'0.01'` and `1` - none of these work. The steps are working correctly on the input fields however.

Is my field incorrectly defined or is there an issue with the field `type: 'input'`?

**Comment by kamilkisiela** [comment]
@sgwatgit Thanks for pointing this. The apiChecking is not properly set. It's my fault. I'm going to fix it soon and release new version.

**Comment by kamilkisiela** [comment]
@sgwatgit At the moment it is impossible to check if min, max or step are being
used only when type === 'number'. So I leave it.

I'm only checking if:
`templateOptions.step` is a number (optional)
`templateOptions.type` is a string (default: text)

**Comment by seangwright** [comment]
@kamilkisiela That's fine by me. Those attributes simply won't do anything if `type === 'text'` so I'm not too worried about it. Everything else looks great - thanks for all the work on this.

**Pull request closed without merging**
